### ISSUE TITLE
Fill opacity set to 0 incorrectly

### ISSUE THREAD

**Issue by hemish11** [AdobeXD/xd-to-flutter-plugin#28] opened 2020-05-15 10:51 UTC
I was experimenting with the plugin first when I add an Ellipse, and added shadow to it. Then I changed its color. But when I exported it, the hexadecimal code was copied as `#00FF9090` and not as `#FFFF9090`. So the circle's color was transparent its shadow as visible.
Screenshot of Adobe XD is as follows:
<img width="1552" alt="Screenshot 2020-05-15 at 4 10 40 PM" src="https://user-images.githubusercontent.com/46677360/82042741-09c8c680-96c8-11ea-85d7-46501012efbb.png">
The Screenshot of the Code is as follows:
<img width="691" alt="Screenshot 2020-05-15 at 4 11 27 PM" src="https://user-images.githubusercontent.com/46677360/82042547-adfe3d80-96c7-11ea-9fa3-33695dab598d.png">
I had highlighted the hexadecimal code.
And here is the screenshot of the simulator in which app is running:
<img width="396" alt="Screenshot 2020-05-15 at 4 11 47 PM" src="https://user-images.githubusercontent.com/46677360/82042645-e1d96300-96c7-11ea-8835-8cc8abfec70f.png">
**Note:** And also there is comma missing after blurRadius This is not a big issue but it affects auto formatting of flutter.

**Comment by gskinner** [comment] 2020-05-15 17:04
Ah ha! Someone else posted a screen shot that showed something similar, and I was wondering how to reproduce it. Would you mind sharing your XD file, just to be certain we can reproduce this? This definitely looks like a bug.

**Comment by gskinner** [comment] 2020-05-15 19:41
I've been unable to reproduce this, so I'd really appreciate either more detailed reproduction steps, or an XD file that shows it. Thanks!

![image](https://user-images.githubusercontent.com/157128/82089949-d5e2a680-96b1-11ea-9d45-9a4a939e1f13.png)

**Comment by gskinner** [comment] 2020-05-15 20:17
Here's a repro case: https://github.com/yashpaneliya/XD_to_Flutter_example

**Comment by gskinner** [comment] 2020-05-15 20:42
This has been resolved and will be part of the next build.

In short: If a background blur was added, and then disabled, the calculation for the fill opacity was still including the blur's fill opacity.

**Comment by hemish11** [comment] 2020-05-16 05:40
> This has been resolved and will be part of the next build.
> 
> In short: If a background blur was added, and then disabled, the calculation for the fill opacity was still including the blur's fill opacity.

Did you also solved the issue that I mentioned with comma? Though it is not a big issue but at the time of auto formatting due to that comma it does not auto format properly.

**Comment by cyrsis** [comment] 2020-05-16 07:53
I solve it by opacity according the colors in XD in my plugin

Kind of working great

**Comment by gskinner** [comment] 2020-05-16 16:22
@hemish11 - forgot the comma. Thanks for the reminder. Fixed in 1b13c25be2349d103e3287666d14ad3336e656c0

**Closed** 2020-05-25 15:19 UTC
Labels: bug, resolved
