### ISSUE TITLE
Vector shape shifting vertically in output

### ISSUE THREAD

**Issue by adnanhaddad** [AdobeXD/xd-to-flutter-plugin#115] opened 2021-05-16 16:31 UTC
## Bug Description

When I export the widgets from Adobe XD to Flutter, I notice that everything works except for the text. It has at the end a couple of missing charachters. I tried solving this by importing the fonts into pubspec.yaml but some texts still don't show.
I am using "SF Pro Display" with three different weights
Any Idea on how to get this right?

## To Reproduce

Type any text with "SF Pro Display" font
Export widget to Flutter

## Sample XD File or Screenshots

![image](https://user-images.githubusercontent.com/33404398/118404346-df12a480-b672-11eb-9083-6159b7565112.png)

Here you can see that the bottom two texts are being displayed just fine but the top one is missing an exclamation mark and the one below is missing an entire word.

## Console Output

{}
https://api.tiled.co/v2
https://app.tiled.co

## Versions:

 - OS: [Windows 10 Education]
 - XD: [40.0.22.12]
 - Plugin: [2.0.0] 
 - Flutter: [10.0.19042.985]]

**Comment by adnanhaddad** [comment] 2021-05-16 20:53
Edit: solved this just by using another font (NOT all fonts work though...)

**Comment by adnanhaddad** [comment] 2021-05-16 20:55
Now I'm facing another weird problem. why is the white wave in Flutter so much higher than in Adobe XD? 
![image](https://user-images.githubusercontent.com/33404398/118412354-ca95d280-b699-11eb-9d1d-1efdba163a1d.png)

**Comment by gskinner** [comment] 2021-05-17 01:41
Generally missing characters is just due to slight differences in rendering (or screen size) causing characters to wrap. I'd recommend dealing with that by using "fixed size" text boxes, and give them some extra breathing room. That lets you control things pretty granularly within your design.

I'm not sure why that curve is moving upward. From what I can see, it shouldn't. If you're able to share a simplified XD file, I can take a look and see if it's an issue on our end.

**Comment by adnanhaddad** [comment] 2021-05-17 07:46
Thanks for replying. Using a fixed size text box would mean a non-dynamic text adjusments in the future, right? Say I have the word "hey" in a fixed box and now I wanna change it to "Welcome!" then the only charachters that will be displayed are "Wel" because that's the size of the box. Or do I misunderstand this?
----
I attached an exact copy of the widget that causing the other moving up behavior. 
[test.zip](https://github.com/AdobeXD/xd-to-flutter-plugin/files/6492068/test.zip)

**Comment by gskinner** [comment] 2021-05-17 14:39
That's the nice thing about the fixed size box — you can set up the box to be oversized to accommodate more text. It's also more intuitive to work with responsive layout (since you can size/position the box properly, vs relying on a size that shifts as the text changes).

It maps better to what Flutter expects too, since text in Flutter is contained in a box.

**Comment by gskinner** [comment] 2021-06-21 15:39
I just tested this, and I'm not seeing the same issue:
![image](https://user-images.githubusercontent.com/157128/122788572-b2eed280-d273-11eb-9e2c-aa778215d92e.png)

The white wave is positioned relative to the bottom, so it will push upwards as the screen size decreases, but that wouldn't fully account for what's shown in your screenshot (the screen is only about 25px shorter than the design). In your screenshot it _looks_ like either the vector is actually extended somehow (I can't think how that would happen), or like something is pushing both the white wave and red rectangle behind it up, exposing more white background below them (also not sure how that would happen).

Without being able to reproduce this, I'm not sure what's going on. I don't suppose you have any more info you could share?

**Comment by gskinner** [comment] 2021-06-23 21:46
I'm going to close this as unable to reproduce, but please don't hesitate to reopen with additional info.

**Closed by gskinner** 2021-06-23 21:46 UTC
Labels: bug, requires info
