### ISSUE TITLE
Does not export artboards in "big" XD projects

### ISSUE THREAD

**Issue by alejandro-oria** [AdobeXD/xd-to-flutter-plugin#32] opened 2020-05-15 20:54 UTC
I have tried to export a single artboard and no message appears when I click on "Export widget". I have already specified the flutter project path, etc. I tried with another Adobe XD project with less artboards and no problem found, it works.

**Comment by gskinner** [comment] 2020-05-15 21:03
Is there any chance you could share the large file? I'd love to test it out. We haven't seen that behaviour previously.

**Comment by alejandro-oria** [comment] 2020-05-15 21:12
> Is there any chance you could share the large file? I'd love to test it out. We haven't seen that behaviour previously.

I have sent you an email with the file attached.

**Comment by gskinner** [comment] 2020-05-15 21:15
Thanks! I took a quick look, and it looks like this is generating the same error as #24.
`Plugin TypeError: Cannot read property 'widgetName' of undefined`

I'm going to close this issue as a duplicate of #24, but the file you sent should be helpful in tracking down whats happening here.

**Closed by gskinner** 2020-05-15 21:15 UTC

**Comment by gskinner** [comment] 2020-05-16 16:48
Further testing of the provided file shows this is actually a duplicate of #4 

![image](https://user-images.githubusercontent.com/157128/82125361-bbb4d100-9762-11ea-98d9-09d73af1e2e5.png)
