### ISSUE TITLE
Code generation mapping to real components for cleaner code

### ISSUE THREAD

**Issue by Qwin** [AdobeXD/xd-to-flutter-plugin#31] opened 2020-05-15 17:03 UTC
I was wondering if this plugin will support converting code to actual existing widgets instead of transforming everything. There should be a standard in XD where when you have for instance a certain naming for a widget it would know its a button and uses that widget instead of transform and just applies the styling to it. 

Or better yet come out with a material UIKit for XD that matches all controls of flutter and each item matches the real controls of flutter. When using a custom one it will use transform to draw it.

**Comment by gskinner** [comment] 2020-05-15 17:06
Have a look at #13 - layout will help make things more useful, and we definitely have ideas (similar to what you've proposed) around mapping elements in XD to existing widgets.

**Comment by gskinner** [comment] 2020-05-15 17:07
I'm going to close this as a duplicate of #13, but appreciate the feedback, and welcome you to comment there with additional ideas.

**Closed by gskinner** 2020-05-15 17:07 UTC
