### ISSUE TITLE
Error when opening Adobe XD Exported Menus. (Flutter)

### ISSUE THREAD

**Issue by origamisimplicity** [AdobeXD/xd-to-flutter-plugin#66] opened 2020-07-22 11:32 UTC
**Expected results:** Screen change to Main Screen

**Actual results: I/flutter ( 5763):** unhandled element filter; Picture key: StringPicture(String#19741, colorFilter: null)

I have a simple button calling the menu that i exported from Adobe XD.

```
 if (numid.isNotEmpty) {
        print("valid");
        Navigator.push(context, MaterialPageRoute(builder: (context) => MainScreen()));
      } else {
        print("invalid");
```

**Comment by gskinner** [comment] 2020-07-27 14:57
I haven't seen this before - are you able to provide an XD file that reproduces this issue?

**Comment by gskinner** [comment] 2020-11-28 18:22
Closing due to lack of info

**Closed by gskinner** 2020-11-28 18:22 UTC
Labels: bug, requires info

**Comment by Zabadam** [comment] 2021-02-05 09:26
I have experienced this issue recently. No obvious fault occurs in the program's appearance nor function, but a similar throw:
`I/flutter (19544): unhandled element filter; Picture key: StringPicture(String#aee9a, colorFilter: null)`

For a while I have been ignoring it (look at later) but reading #66 here via a web search gave me plenty insight to the issue.

In my code I have:
```
// Plus Icons placed in between Ingredient Tiles in the Recipe Section
// TODO: Review sizing of Text('+') in context of ListIngredients on a smaller screen.
const String plusSVG =
    '<svg viewBox="0.0 0.0 10.0 10.0" ><defs><filter id="shadow"><feDropShadow dx="0" dy="0" stdDeviation="3"/></filter></defs><path transform="translate(4.0, 2.0)" d="M 2.000487804412842 -1.99951171875 L 0.0004903078079223633 -1.99951171875 L 0.0004903078079223633 2.000488042831421 L -3.999503612518311 2.000488042831421 L -3.999503612518311 4.00048828125 L 0.0004903078079223633 4.00048828125 L 0.0004903078079223633 8.00048828125 L 2.000487804412842 8.00048828125 L 2.000487804412842 4.00048828125 L 6.000481605529785 4.00048828125 L 6.000481605529785 2.000488042831421 L 2.000487804412842 2.000488042831421 L 2.000487804412842 -1.99951171875 Z" fill="#ffffff" fill-opacity="0.8" stroke="none" stroke-width="1" stroke-miterlimit="10" stroke-linecap="butt" filter="url(#shadow)"/></svg>';

class IconPlus extends StatelessWidget {
  final double size;

  IconPlus({Key key, this.size}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // WIP
    // return SizedBox(
    //   width: size * 2,
    //   height: size * 2,
    //   child: FittedBox(child: Text('+', style: TextStyle(fontSize: 50))),
    return Container(
      width: size,
      height: size,
      child: SvgPicture.string(
        plusSVG,
        allowDrawingOutsideViewBox: true,
      ),
    );
  }
}
```
The SVG code is obviously exported from Adobe XD, but removing dependency on SVG here will remove dependency in my project anyway (XD was immensely helpful early in my organizing, but I have since rewritten everything but this icon).

That said, removing the `<def>` tags (and child `<filter>`) as well as removing the caboose `filter` property resolves the error.

P.S. Upon second thought, the error was unnoticeable because this IconPlus was rendered so small, but of course the drop shadow was not present--neither before nor after removal of code.
