### ISSUE TITLE
Prototype linking & interaction is not working at all

### ISSUE THREAD

**Issue by Charles99p** [AdobeXD/xd-to-flutter-plugin#73] opened 2020-08-26 11:53 UTC
![scrn1](https://user-images.githubusercontent.com/70269107/91300925-b0415f00-e7c1-11ea-9db6-8b1a28c9ea19.jpg)
![scrn2](https://user-images.githubusercontent.com/70269107/91300930-b20b2280-e7c1-11ea-89cc-50a1a7ec47ca.jpg)

It is not taking prototype links to other screens, Only initial screen is visible at run time. After that when I click the section which is given link is not changing.

I tried with previous version, **adobe_xd: ^0.1.3**  prototype links are working fine. But with the updated version it is having issues " **adobe_xd: 1.0.0+1**"
 

Please let me know the fix for this..

Thanks

**Comment by gskinner** [comment] 2020-11-28 18:36
I know it's been a while, but is there any chance you could share an XD file demonstrating this issue (the simpler the better)? Also, can you confirm this is using v1.0.0 of the plugin?

Interactions are working in the sample app, so I'd like to try to isolate what's different in your file.

Thanks!

**Comment by JohnnyOpcode** [comment] 2020-12-04 03:50
I'd like to see an OnTap interaction in the sample app. The sample can then serve as a baseline (always) what is working and what is not.

Thx,
Johnny

**Comment by gskinner** [comment] 2020-12-05 20:38
The existing demo app has a couple of tap interactions (on "Gear Guide" and the back button).

**Comment by gskinner** [comment] 2020-12-05 21:02
I'd like to tackle this one in v1.0.1 @Charles99p , but would need more info to isolate it.

**Comment by JohnnyOpcode** [comment] 2020-12-05 21:40
> The existing demo app has a couple of tap interactions (on "Gear Guide" and the back button).

The Gear Guide uses the linking widget. I used a play audio in my design (svg widgets) and it does not fire. Maybe onTap doesn't work yet.

Thx,
Johnny

**Comment by gskinner** [comment] 2020-12-06 19:57
@JohnnyOpcode - ah! I think you're asking for an example of the onTap parameter, right? If so, could you please file a new issue for that? This issue is about prototype interactions.

**Comment by gskinner** [comment] 2020-12-14 17:34
Closing this because it doesn't have a sample file, or sufficient information to reproduce the problem. Please feel free to reopen with more info.

**Closed by gskinner** 2020-12-14 17:34 UTC
Labels: bug, requires info

**Comment by gskinner** [comment] 2020-12-15 17:41
@JohnnyOpcode - I added (and resolved) #87
