### ISSUE TITLE
                        Pinned.fromSize(

### ISSUE THREAD

**Issue by EngMotassem** [AdobeXD/xd-to-flutter-plugin#68] opened 2020-08-01 00:27 UTC
generated code 

import 'package:adobe_xd/pinned.dart';

**Comment by gskinner** [comment] 2020-11-28 18:23
I'm not sure what this is asking or reporting. Closing, but feel free to reopen with more info. Possibly this is a duplicate of #74 ?

**Closed by gskinner** 2020-11-28 18:23 UTC
Labels: bug, requires info

**Comment by iinfinitii** [comment] 2021-08-17 09:28
Add dependency adobe_xd: ^1.1.0+1 into pubspec.yaml and run flutter pub get
