### ISSUE TITLE
Repeat Grids no longer scrolls properly after adding my Map data

### ISSUE THREAD

**Issue by PearlByte** [AdobeXD/xd-to-flutter-plugin#69] opened 2020-08-07 01:49 UTC
**Describe the Bug**
After updating to v1.0.0, using the same Adobe XD file, the Repeat Grid is no longer scrollable. I'm adding the same Map data structure that I was using before. The grid is scrollable once I export it using the tool from Adobe XD and looks like this:

child: Wrap(
                alignment: WrapAlignment.center,
                spacing: 20,
                runSpacing: 20,
                children:
                    [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}].map((map) {
                  return SizedBox(... etc...

Once I add the following, the scrolling breaks:

child: Wrap(
                    alignment: WrapAlignment.center,
                    spacing: 20,
                    runSpacing: 20,
                    children: **myMapCategories.keys**.map((map) {
                      }
                  return SizedBox(... etc...

This worked perfectly in v0.1.0. I tried this with a very simple case using only the Repeat Grid component and adding my Map.

**To Reproduce**
Add a Map data structure to a Repeat Grid to display actual dynamic data... the scrolling no longer works.

**OS & XD Version:**
OS: MacOS 10.15.5
XD: 31.1.12.13

**Other Information:**
I see that in your example that was updated for v1.0.0, the data is static so it seems like the scrolling works. Try adding dynamic data from a Map or List.

**Comment by gskinner** [comment] 2020-12-05 20:36
If you have a simplified XD file I can use to repro this, it would help with tracking the issue down.

**Comment by gskinner** [comment] 2020-12-14 18:07
Looking at your code, can you confirm whether you stripped the data out of the child list items? If not, then it looks like the export isn't expecting any dynamic data. For example, the output from the example file looks like this:

```
children: [
	{
	  'value': '10',
	  'label': 'Days',
	},
	{
	  'value': '160',
	  'label': 'Miles',
	},
	{
	  'value': '5',
	  'label': 'Camps',
	},
	{
	  'value': '2',
	  'label': 'Bears',
	}
  ]
```

**Comment by gskinner** [comment] 2020-12-14 18:18
Tested modifying the data in the CampVibes example, and it appeared to work as expected. I'm going to close this based on the above assumption. Please feel free to re-open with additional info.

**Closed by gskinner** 2020-12-14 18:18 UTC
Labels: bug, requires info

**Comment by PearlByte** [comment] 2020-12-14 21:14
Yes, I did strip out the data out of the child list items to use my Map
structure and have dynamic data. But it no longer allows scrolling, it used
to in the previous release.

Regards,
Zee
PearlByte, Inc.

**Comment by gskinner** [comment] 2020-12-15 17:14
I think I understand: You set up a list in XD, and then when you add more items to it than it had in the design, it doesn't automatically scroll (but it did in the previous version). If that's correct, I'll reopen and test this.

**Comment by gskinner** [comment] 2020-12-15 18:11
I just did a quick test for this, and it appears to work correctly. I'll need more info to reproduce what you're seeing.

![scrollingList](https://user-images.githubusercontent.com/157128/102254677-32b37300-3ec6-11eb-8a3b-27ac2f62da5d.gif)
