### ISSUE TITLE
Plugin doesn't let me export, it doesn't show any message out of console

### ISSUE THREAD

**Issue by steelpwner** [AdobeXD/xd-to-flutter-plugin#72] opened 2020-08-08 06:06 UTC
I'm here to report this bug:

Plugin ReferenceError: xdNode is not defined
    at l (<settings>\plugins\6eaf77ea\main.js:1:89631)
    at a._serialize (<settings>\plugins\6eaf77ea\main.js:1:89240)
    at a.serialize (<settings>\plugins\6eaf77ea\main.js:1:22069)
    at u._decorate (<settings>\plugins\6eaf77ea\main.js:1:11998)
    at u.serialize (<settings>\plugins\6eaf77ea\main.js:1:11844)
    at <settings>\plugins\6eaf77ea\main.js:1:12136
    at Array.forEach (<anonymous>)
    at e.Artboard._getChildList (<settings>\plugins\6eaf77ea\main.js:1:12113)
    at e.Artboard._getChildStack (<settings>\plugins\6eaf77ea\main.js:1:12334)
    at e.Artboard._serializeWidgetBody (<settings>\plugins\6eaf77ea\main.js:1:75136)

It appears when i'm trying to export my project, doesn't show any message and doesn't export anything, i got the last adobe XD version and downloaded plugin from the plugins section.

Am uploading ss for you to see what's happening

![image](https://user-images.githubusercontent.com/42214819/89703742-2e24ef80-d913-11ea-9b69-22f20f1327b5.png)

and when i click export

![image](https://user-images.githubusercontent.com/42214819/89703752-3f6dfc00-d913-11ea-946d-0418c130f680.png)

it doesn't show any message and tought was my problem because of it... then tried like 3 or 4 times to do the same and all of em says that reference error.

please, help me with this...

Thank you!

**Comment by IonVillarreal** [comment] 2020-08-15 13:52
same error in Adobe XD version 31.2.12.4 for Mac

<img width="714" alt="image" src="https://user-images.githubusercontent.com/12217695/90313733-e555d380-dedc-11ea-90b8-f8eae7dde14c.png">

**Comment by clearnetinc** [comment] 2020-10-08 14:33
Same issue here. There is no activity at all it just goes blank and when you check /lib folder there is nothing at all.

**HELP!!!**

**Comment by jhonatanluiz** [comment] 2020-10-09 18:12
some solution to this issue?

**Comment by FXschwartz** [comment] 2020-10-26 19:57
Same issue on Windows 10. No error message at all and nothing in the selected lib folder when exporting.

**Comment by gopal-c** [comment] 2020-10-30 06:20
Yes me too. On Windows 10 Home. Using Adobe XD 34.1.12. And Flutter 1.22.2.
No error message.

**Comment by gskinner** [comment] 2020-11-28 18:32
This looks like it a duplicate of #71 .

I know it's been awhile since this was posted (see #79 for some info), but would anyone be able to confirm that they are using v1.0.0, and if so, provide me with an XD file that's slimmed down to the minimum that will throw the error? That will help me isolate it, confirm it's the same as #71, and ultimately fix it.

Thanks!

**Comment by edhaz** [comment] 2020-12-08 11:43
I can confirm I get this error using XD 35.2.12.6 on macOS 11.0.1 with the plugin version v1.0.0.

**Comment by edhaz** [comment] 2020-12-08 11:59
Here's a stripped down version:
[prototype-test.xd.zip](https://github.com/AdobeXD/xd-to-flutter-plugin/files/5659109/prototype-test.xd.zip)

**Comment by gskinner** [comment] 2020-12-09 17:07
Thanks @edhaz ! I'll take a look at this, and have a fix in the v1.0.1 build.

If anyone else can similarly share their files it will help me confirm that there is only one cause for this issue.

**Comment by gskinner** [comment] 2020-12-14 17:24
I just added a fix for the issue presented by the file @edhaz provided. Wound up being an error in our error handling. _sigh_

If anyone else has sample files, I'm happy to test them to ensure they are covered by this fix.

**Comment by Boondoge** [comment] 2020-12-17 12:54
> 
> 
> I just added a fix for the issue presented by the file @edhaz provided. Wound up being an error in our error handling. _sigh_
> 
> You can work around it for now by ensuring there are no unsupported transitions or eases on your prototype interactions (ex. auto animate).
> 
> If anyone else has sample files, I'm happy to test them to ensure they are covered by this fix.

This solved it for me, could not export any individually either. Even those that had simple transition and no auto-animate so long as there were artboards that used auto-animate.

No errors though, it just doesn't do anything.

**Closed** 2021-05-03 16:23 UTC
Labels: bug, requires info, resolved
