### ISSUE TITLE
Cannot export xd to flutter

### ISSUE THREAD

**Issue by SpaceKestrel72** [AdobeXD/xd-to-flutter-plugin#81] opened 2020-12-06 17:07 UTC
I guess this is not new issue, but this is basically it.  I click export all widgets and nothing happend. 
Can devs take it seriosly? My job and not mine only depend on that stuff.

Plugin TypeError: Cannot read property 'parsed' of null
    at E (<settings>\plugins\6eaf77ea\main.js:1:72579)
    at P (<settings>\plugins\6eaf77ea\main.js:1:73861)
    at E (<settings>\plugins\6eaf77ea\main.js:1:72805)
    at e.parse (<settings>\plugins\6eaf77ea\main.js:1:72090)
    at Object.exportAll (<settings>\plugins\6eaf77ea\main.js:1:70488)
    at async e.exports.exportAll (<settings>\plugins\6eaf77ea\main.js:1:47406)

**Comment by gskinner** [comment] 2020-12-06 17:46
This is a duplicate of #78 .

Any chance you can share the XD file that's causing this (ideally simplified as much as possible)? I can dig into why this might be happening, but having a file that concretely reproduces it would be very helpful.

Thanks!

**Comment by gskinner** [comment] 2020-12-14 16:26
Closing in favour of #78.

**Closed by gskinner** 2020-12-14 16:26 UTC
Labels: bug, requires info
